# Read and Prepare the Data

In [1]:
# Common imports
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd

In [2]:
#Reading Data
data = pd.read_csv("heartbeat.csv")

In [3]:
data.shape

(9026, 188)

In [4]:
data.head()

T1     T2     T3      T4      T5      T6      T7      T8      T9  \
0  0.987  0.892  0.461  0.1130  0.1490  0.1900  0.1650  0.1620  0.1470   
1  1.000  0.918  0.621  0.1330  0.1050  0.1250  0.1170  0.0898  0.0703   
2  1.000  0.751  0.143  0.1040  0.0961  0.0519  0.0442  0.0416  0.0364   
3  1.000  0.740  0.235  0.0464  0.0722  0.0567  0.0103  0.0155  0.0284   
4  1.000  0.626  0.276  0.3250  0.4310  0.3900  0.3940  0.3580  0.3740   

      T10  ...  T179  T180  T181  T182  T183  T184  T185  T186  T187  Target  
0  0.1380  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0     0.0  
1  0.0781  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0     0.0  
2  0.0857  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0     0.0  
3  0.0155  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0     0.0  
4  0.3620  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0     0.0  

[5 rows x 188 columns]

In [5]:
y = data['Target']
x = data.drop('Target', axis=1)

## Splitting the data

In [6]:
from sklearn.model_selection import train_test_split

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.3)

## Data Transformation

In [7]:
#Converting Target variables to array with integer type
train_y = np.array(train_y)
test_y = np.array(test_y)

train_y = train_y.astype(np.int32)
test_y = test_y.astype(np.int32)

In [8]:
#Checking the first 10 values of the train_y data set
train_y[0:10]

array([0, 2, 0, 0, 3, 2, 0, 0, 2, 0], dtype=int32)

In [9]:
#Converting input variables to a 2-D array with float data type
train_x= np.array(train_x)
test_x= np.array(test_x)

train_x = train_x.astype(np.float32)
test_x = test_x.astype(np.float32)

In [10]:
train_x

array([[0.931, 0.844, 0.647, ..., 0.   , 0.   , 0.   ],
       [1.   , 0.986, 0.721, ..., 0.   , 0.   , 0.   ],
       [1.   , 0.928, 0.617, ..., 0.   , 0.   , 0.   ],
       ...,
       [1.   , 0.951, 0.495, ..., 0.   , 0.   , 0.   ],
       [0.24 , 0.421, 0.607, ..., 0.   , 0.   , 0.   ],
       [0.927, 0.767, 0.595, ..., 0.   , 0.   , 0.   ]], dtype=float32)

In [11]:
#Converting Data to have 3 dimensions for Keras:

train_x = np.reshape(train_x, (train_x.shape[0], train_x.shape[1], 1))
test_x = np.reshape(test_x, (test_x.shape[0], test_x.shape[1], 1))

In [12]:
train_x.shape, train_y.shape

((6318, 187, 1), (6318,))

In [13]:
train_x

array([[[0.931],
        [0.844],
        [0.647],
        ...,
        [0.   ],
        [0.   ],
        [0.   ]],

       [[1.   ],
        [0.986],
        [0.721],
        ...,
        [0.   ],
        [0.   ],
        [0.   ]],

       [[1.   ],
        [0.928],
        [0.617],
        ...,
        [0.   ],
        [0.   ],
        [0.   ]],

       ...,

       [[1.   ],
        [0.951],
        [0.495],
        ...,
        [0.   ],
        [0.   ],
        [0.   ]],

       [[0.24 ],
        [0.421],
        [0.607],
        ...,
        [0.   ],
        [0.   ],
        [0.   ]],

       [[0.927],
        [0.767],
        [0.595],
        ...,
        [0.   ],
        [0.   ],
        [0.   ]]], dtype=float32)

In [14]:
# Calculating Baseline
data['Target'].value_counts()/len(data)

0.0    0.581875
4.0    0.178152
2.0    0.160425
1.0    0.061600
3.0    0.017948
Name: Target, dtype: float64

## Creating a normal (cross-sectional) NN Model for Comparison

In [15]:
# Building Model
model = keras.models.Sequential([
    tf.keras.layers.Masking(mask_value=0, input_shape=[187,1]),
    keras.layers.Flatten(input_shape=[187, 1]),
    keras.layers.Dense(20, activation='relu'),
    keras.layers.Dense(5, activation='softmax')   
])

In [16]:
# Fitting Model
np.random.seed(42)
tf.random.set_seed(42)

optimizer = tf.keras.optimizers.Nadam(lr=0.01)
model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=50,
                    validation_data=(test_x, test_y))

Epoch 1/50
198/198 [==============================] - 1s 4ms/step - loss: 0.9292 - accuracy: 0.6701 - val_loss: 0.5879 - val_accuracy: 0.8010
Epoch 2/50
198/198 [==============================] - 0s 1ms/step - loss: 0.5233 - accuracy: 0.8267 - val_loss: 0.4950 - val_accuracy: 0.8357
Epoch 3/50
198/198 [==============================] - 0s 1ms/step - loss: 0.4609 - accuracy: 0.8493 - val_loss: 0.4837 - val_accuracy: 0.8449
Epoch 4/50
198/198 [==============================] - 0s 1ms/step - loss: 0.4113 - accuracy: 0.8652 - val_loss: 0.4795 - val_accuracy: 0.8479
Epoch 5/50
198/198 [==============================] - 0s 1ms/step - loss: 0.3598 - accuracy: 0.8879 - val_loss: 0.4430 - val_accuracy: 0.8641
Epoch 6/50
198/198 [==============================] - 0s 1ms/step - loss: 0.3544 - accuracy: 0.8872 - val_loss: 0.4047 - val_accuracy: 0.8804
Epoch 7/50
198/198 [==============================] - 0s 1ms/step - loss: 0.3354 - accuracy: 0.8946 - val_loss: 0.4166 - val_accuracy: 0.8763
Epoch 

In [17]:
# Evaluating the model
scores = model.evaluate(test_x, test_y, verbose=0)
scores

print("%s: %.2f" % (model.metrics_names[0], scores[0]))
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

loss: 0.36
accuracy: 90.69%


# LSTM Model

### Make sure to add the masking layer to the model!

In [18]:
from tensorflow.keras.callbacks import EarlyStopping

earlystop = EarlyStopping(monitor='val_loss', patience=5, verbose=1, mode='auto')

callback = [earlystop]

In [19]:
#building Model
n_steps = 187
n_inputs = 1

model = keras.models.Sequential([
    tf.keras.layers.Masking(mask_value=0, input_shape=[n_steps, n_inputs]),
    keras.layers.LSTM(20, return_sequences=True, input_shape=[n_steps, n_inputs]),
    keras.layers.LSTM(20, return_sequences=True),
    keras.layers.LSTM(10),
    keras.layers.Dense(5, activation='softmax')
])

In [20]:
#Fitting Model
np.random.seed(42)
tf.random.set_seed(42)

optimizer = keras.optimizers.Nadam(lr=0.001)

model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=50,
                   validation_data = (test_x, test_y), callbacks=callback)

Epoch 1/50
198/198 [==============================] - 68s 294ms/step - loss: 1.2269 - accuracy: 0.5835 - val_loss: 1.0934 - val_accuracy: 0.5735
Epoch 2/50
198/198 [==============================] - 57s 289ms/step - loss: 1.0684 - accuracy: 0.5846 - val_loss: 1.1179 - val_accuracy: 0.4900
Epoch 3/50
198/198 [==============================] - 49s 248ms/step - loss: 1.0618 - accuracy: 0.5868 - val_loss: 1.0803 - val_accuracy: 0.5757
Epoch 4/50
198/198 [==============================] - 52s 264ms/step - loss: 1.0405 - accuracy: 0.6063 - val_loss: 1.0303 - val_accuracy: 0.6182
Epoch 5/50
198/198 [==============================] - 50s 253ms/step - loss: 0.9433 - accuracy: 0.6721 - val_loss: 0.9137 - val_accuracy: 0.7049
Epoch 6/50
198/198 [==============================] - 66s 334ms/step - loss: 0.8892 - accuracy: 0.7086 - val_loss: 0.8435 - val_accuracy: 0.7138
Epoch 7/50
198/198 [==============================] - 73s 368ms/step - loss: 0.8107 - accuracy: 0.7305 - val_loss: 0.8134 - val_ac

In [21]:
# Evaluating the model

scores = model.evaluate(test_x, test_y, verbose=0)

scores

print("%s: %.2f" % (model.metrics_names[0], scores[0]))
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

loss: 0.42
accuracy: 87.22%


# GRU Model

### Make sure to add the masking layer to this model too!

In [22]:
# Building Model
n_steps = 187
n_inputs = 1

model = keras.models.Sequential([
    tf.keras.layers.Masking(mask_value=0, input_shape=[n_steps, n_inputs]),
    keras.layers.GRU(20, return_sequences=True, input_shape=[n_steps, n_inputs]),
    keras.layers.GRU(20, return_sequences=True),
    keras.layers.GRU(20, return_sequences=True),
    keras.layers.GRU(5, activation='softmax')
])

In [23]:
#Fitting Model
np.random.seed(42)
tf.random.set_seed(42)

optimizer = keras.optimizers.Nadam(lr=0.001)

model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=50,
                   validation_data = (test_x, test_y), callbacks=callback)

Epoch 1/50
198/198 [==============================] - 72s 312ms/step - loss: 1.2975 - accuracy: 0.5271 - val_loss: 1.0522 - val_accuracy: 0.5894
Epoch 2/50
198/198 [==============================] - 59s 298ms/step - loss: 1.0147 - accuracy: 0.6127 - val_loss: 0.9108 - val_accuracy: 0.6979
Epoch 3/50
198/198 [==============================] - 59s 298ms/step - loss: 0.8326 - accuracy: 0.7235 - val_loss: 0.7328 - val_accuracy: 0.7770
Epoch 4/50
198/198 [==============================] - 59s 298ms/step - loss: 0.7071 - accuracy: 0.7833 - val_loss: 0.6672 - val_accuracy: 0.7943
Epoch 5/50
198/198 [==============================] - 59s 301ms/step - loss: 0.6397 - accuracy: 0.8058 - val_loss: 0.6478 - val_accuracy: 0.8013
Epoch 6/50
198/198 [==============================] - 59s 298ms/step - loss: 0.6202 - accuracy: 0.8065 - val_loss: 0.6348 - val_accuracy: 0.8047
Epoch 7/50
198/198 [==============================] - 59s 296ms/step - loss: 0.5779 - accuracy: 0.8254 - val_loss: 0.5890 - val_ac

In [24]:
# Evaluating the model

scores = model.evaluate(test_x, test_y, verbose=0)

scores

print("%s: %.2f" % (model.metrics_names[0], scores[0]))
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

loss: 0.33
accuracy: 90.21%
