# Read and Prepare the Data

In [1]:
# Common imports
import numpy as np
import pandas as pd

np.random.seed(42)

In [2]:
#We will predict the target variablein the dataset

transport = pd.read_csv("transportation.csv")
transport.head()

androidsensoraccelerometermean  androidsensoraccelerometermin  \
0                        9.701276                       9.520186   
1                        9.240731                       6.927889   
2                       10.397750                       8.649993   
3                       10.197564                       9.977808   
4                        9.812239                       8.290205   

   androidsensoraccelerometermax  androidsensoraccelerometerstd  \
0                       9.826383                       0.074273   
1                      11.371441                       1.157460   
2                      11.105722                       0.614978   
3                      10.417198                       0.137675   
4                      11.913782                       1.016052   

   androidsensorgyroscopemean  androidsensorgyroscopemin  \
0                    0.021729                   0.012970   
1                    0.114340                   0.018950   
2                    0.301824                   0.260226   
3                    0.017742                   0.003502   
4                    0.109497                   0.005390   

   androidsensorgyroscopemax  androidsensorgyroscopestd  soundmean   soundmin  \
0                   0.033699                   0.005727  88.111708  88.111708   
1                   0.291155                   0.071189  89.771860  89.771860   
2                   0.339794                   0.021420  89.797764  89.797764   
3                   0.039349                   0.009800  89.746162  89.746162   
4                   0.277880                   0.070489  89.768758  89.768758   

    soundmax  soundstd target  
0  88.111708  0.000000  Train  
1  89.771860  0.008778    Bus  
2  89.797764  0.039875    Car  
3  89.746162  0.122969  Train  
4  89.768758  1.023191    Bus

In [3]:
#Creating Test and Train Split

from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(transport, test_size=0.3)

In [4]:
#Seperating the target Variable from the dataset
train_target = train_set[['target']]
test_target = test_set[['target']]

train_inputs = train_set.drop(['target'], axis=1)
test_inputs = test_set.drop(['target'], axis=1)

In [5]:
#Checking for. null Values
train_set.isna().sum()

androidsensoraccelerometermean    0
androidsensoraccelerometermin     0
androidsensoraccelerometermax     0
androidsensoraccelerometerstd     0
androidsensorgyroscopemean        0
androidsensorgyroscopemin         0
androidsensorgyroscopemax         0
androidsensorgyroscopestd         0
soundmean                         0
soundmin                          0
soundmax                          0
soundstd                          0
target                            0
dtype: int64

In [6]:
#Checking for. null Values
test_set.isna().sum()

androidsensoraccelerometermean    0
androidsensoraccelerometermin     0
androidsensoraccelerometermax     0
androidsensoraccelerometerstd     0
androidsensorgyroscopemean        0
androidsensorgyroscopemin         0
androidsensorgyroscopemax         0
androidsensorgyroscopestd         0
soundmean                         0
soundmin                          0
soundmax                          0
soundstd                          0
target                            0
dtype: int64

In [7]:
#Pipeline Imports
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

from sklearn.preprocessing import FunctionTransformer

In [8]:
#Checking the datatypes of Train/test
train_inputs.dtypes

androidsensoraccelerometermean    float64
androidsensoraccelerometermin     float64
androidsensoraccelerometermax     float64
androidsensoraccelerometerstd     float64
androidsensorgyroscopemean        float64
androidsensorgyroscopemin         float64
androidsensorgyroscopemax         float64
androidsensorgyroscopestd         float64
soundmean                         float64
soundmin                          float64
soundmax                          float64
soundstd                          float64
dtype: object

In [9]:
# Identifying the numerical columns
numeric_columns = train_inputs.select_dtypes(include=[np.number]).columns.to_list()

In [10]:
numeric_columns

['androidsensoraccelerometermean',
 'androidsensoraccelerometermin',
 'androidsensoraccelerometermax',
 'androidsensoraccelerometerstd',
 'androidsensorgyroscopemean',
 'androidsensorgyroscopemin',
 'androidsensorgyroscopemax',
 'androidsensorgyroscopestd',
 'soundmean',
 'soundmin',
 'soundmax',
 'soundstd']

In [11]:
#Using Numeric Transformer
numeric_transformer = Pipeline(steps=[
                ('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())])

In [12]:
preprocessor = ColumnTransformer([
        ('num', numeric_transformer, numeric_columns)],
        remainder='passthrough')

In [13]:
#Fit_transform on Train Data
train_x = preprocessor.fit_transform(train_inputs)

train_x

array([[-1.74886686e-01,  2.77326456e-03, -5.99315610e-02, ...,
         3.94770197e-01,  5.25446848e-01,  6.62693768e-01],
       [ 5.30439796e+00, -3.81970427e+00,  9.68226289e+00, ...,
        -2.01473940e+00, -2.02531331e+00, -4.59510230e-01],
       [-6.89177749e-01,  5.48634204e-01, -4.96676441e-01, ...,
         7.61753788e-01,  7.45506062e-01, -4.51528627e-01],
       ...,
       [-4.34786689e-01,  6.01754279e-01, -4.54446532e-01, ...,
         2.81158954e-01,  2.65893332e-01,  3.06596409e-01],
       [ 4.54454105e-01, -2.35371258e+00,  2.48388209e+00, ...,
         7.64978162e-01,  7.48723847e-01, -3.77548557e-01],
       [-1.96270300e-01,  4.93180855e-01, -3.99497977e-01, ...,
         7.20156824e-01,  7.48741421e-01, -1.15978071e-01]])

In [14]:
train_x.shape

(3500, 12)

In [15]:
# Transform of the test data
test_x = preprocessor.transform(test_inputs)

test_x

array([[-0.32025512,  0.76100101, -0.4612405 , ..., -0.03946096,
        -0.05407139, -0.45951023],
       [-0.3753657 , -0.16063805, -0.20714456, ...,  0.51621706,
         0.50047109, -0.37680808],
       [-1.01943413,  0.46313497, -0.5521988 , ..., -0.00395826,
        -0.01864124, -0.45951023],
       ...,
       [ 0.00412727,  0.87321484, -0.41794116, ...,  0.13383799,
         0.11887343,  0.10361519],
       [ 0.09581334,  0.91294408, -0.41518271, ...,  0.54215227,
         0.5263533 , -0.41269376],
       [-0.3038126 ,  0.70052755, -0.44874281, ..., -2.0147394 ,
        -2.02531331, -0.45951023]])

In [16]:
test_x.shape

(1500, 12)

In [17]:
#Ordinal Encoding the Target Variable
from sklearn.preprocessing import OrdinalEncoder

ord_enc = OrdinalEncoder()

train_y = ord_enc.fit_transform(train_target)

train_y

array([[3.],
       [4.],
       [3.],
       ...,
       [3.],
       [4.],
       [0.]])

In [18]:
test_y = ord_enc.transform(test_target)

test_y

array([[3.],
       [0.],
       [0.],
       ...,
       [2.],
       [2.],
       [2.]])

In [19]:
train_target.head()

target
1840    Train
2115  Walking
4437    Train
1146    Train
2486  Walking

In [20]:
(train_target['target'].value_counts())/len(train_target)

Still      0.204286
Train      0.201429
Car        0.201143
Walking    0.197714
Bus        0.195429
Name: target, dtype: float64

# Keras DNN model 1

In [21]:
import tensorflow as tf
from tensorflow import keras

# Fixing random seed for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

In [22]:
train_x.shape

(3500, 12)

In [23]:
#Defining the model: for multi-class

model = keras.models.Sequential()

model.add(keras.layers.Input(shape=12))
model.add(keras.layers.Dense(250, activation='relu'))
model.add(keras.layers.Dense(250, activation='relu'))
model.add(keras.layers.Dense(250, activation='relu'))

#final layer with 5 nodes and softmax (as we have 5 categories)
model.add(keras.layers.Dense(5, activation='softmax'))



In [24]:
# Compiling model

#Optimizer:
adam = keras.optimizers.Adam(lr=0.01)
model.compile(loss='sparse_categorical_crossentropy', optimizer=adam, metrics=['accuracy'])

In [25]:
# Fitting the model

history = model.fit(train_x, train_y, 
                    validation_data=(test_x, test_y), 
                    epochs=250, batch_size=1000)

Epoch 1/250
4/4 [==============================] - 1s 163ms/step - loss: 1.5096 - accuracy: 0.3180 - val_loss: 1.1975 - val_accuracy: 0.5020
Epoch 2/250
4/4 [==============================] - 0s 15ms/step - loss: 1.1380 - accuracy: 0.5213 - val_loss: 1.1250 - val_accuracy: 0.5473
Epoch 3/250
4/4 [==============================] - 0s 15ms/step - loss: 1.0739 - accuracy: 0.5576 - val_loss: 1.0251 - val_accuracy: 0.5607
Epoch 4/250
4/4 [==============================] - 0s 16ms/step - loss: 0.9759 - accuracy: 0.5855 - val_loss: 0.9639 - val_accuracy: 0.5853
Epoch 5/250
4/4 [==============================] - 0s 16ms/step - loss: 0.9250 - accuracy: 0.6091 - val_loss: 0.8864 - val_accuracy: 0.6453
Epoch 6/250
4/4 [==============================] - 0s 16ms/step - loss: 0.8634 - accuracy: 0.6493 - val_loss: 0.8526 - val_accuracy: 0.6640
Epoch 7/250
4/4 [==============================] - 0s 16ms/step - loss: 0.8313 - accuracy: 0.6761 - val_loss: 0.8241 - val_accuracy: 0.6820
Epoch 8/250
4/4 [==

4/4 [==============================] - 0s 14ms/step - loss: 0.2044 - accuracy: 0.9290 - val_loss: 0.9028 - val_accuracy: 0.7900
Epoch 118/250
4/4 [==============================] - 0s 15ms/step - loss: 0.2133 - accuracy: 0.9261 - val_loss: 0.9088 - val_accuracy: 0.7993
Epoch 119/250
4/4 [==============================] - 0s 14ms/step - loss: 0.2093 - accuracy: 0.9194 - val_loss: 0.9045 - val_accuracy: 0.7947
Epoch 120/250
4/4 [==============================] - 0s 15ms/step - loss: 0.1906 - accuracy: 0.9366 - val_loss: 0.9046 - val_accuracy: 0.7880
Epoch 121/250
4/4 [==============================] - 0s 15ms/step - loss: 0.2182 - accuracy: 0.9198 - val_loss: 0.9535 - val_accuracy: 0.7920
Epoch 122/250
4/4 [==============================] - 0s 15ms/step - loss: 0.2613 - accuracy: 0.9127 - val_loss: 0.9135 - val_accuracy: 0.7707
Epoch 123/250
4/4 [==============================] - 0s 15ms/step - loss: 0.2208 - accuracy: 0.9132 - val_loss: 0.8119 - val_accuracy: 0.7960
Epoch 124/250
4/4 [=

Epoch 175/250
4/4 [==============================] - 0s 15ms/step - loss: 0.0959 - accuracy: 0.9652 - val_loss: 1.1166 - val_accuracy: 0.8120
Epoch 176/250
4/4 [==============================] - 0s 15ms/step - loss: 0.0849 - accuracy: 0.9698 - val_loss: 1.0829 - val_accuracy: 0.8100
Epoch 177/250
4/4 [==============================] - 0s 14ms/step - loss: 0.0725 - accuracy: 0.9765 - val_loss: 1.0958 - val_accuracy: 0.8127
Epoch 178/250
4/4 [==============================] - 0s 15ms/step - loss: 0.0726 - accuracy: 0.9763 - val_loss: 1.1496 - val_accuracy: 0.8147
Epoch 179/250
4/4 [==============================] - 0s 15ms/step - loss: 0.0769 - accuracy: 0.9751 - val_loss: 1.1470 - val_accuracy: 0.8100
Epoch 180/250
4/4 [==============================] - 0s 15ms/step - loss: 0.0720 - accuracy: 0.9718 - val_loss: 1.1830 - val_accuracy: 0.8140
Epoch 181/250
4/4 [==============================] - 0s 15ms/step - loss: 0.0814 - accuracy: 0.9737 - val_loss: 1.1874 - val_accuracy: 0.8087
Epoch 

Epoch 233/250
4/4 [==============================] - 0s 15ms/step - loss: 0.0936 - accuracy: 0.9664 - val_loss: 1.1891 - val_accuracy: 0.8127
Epoch 234/250
4/4 [==============================] - 0s 14ms/step - loss: 0.0782 - accuracy: 0.9681 - val_loss: 1.2065 - val_accuracy: 0.8047
Epoch 235/250
4/4 [==============================] - 0s 15ms/step - loss: 0.0863 - accuracy: 0.9692 - val_loss: 1.1857 - val_accuracy: 0.8073
Epoch 236/250
4/4 [==============================] - 0s 15ms/step - loss: 0.0807 - accuracy: 0.9710 - val_loss: 1.2489 - val_accuracy: 0.8047
Epoch 237/250
4/4 [==============================] - 0s 14ms/step - loss: 0.1007 - accuracy: 0.9600 - val_loss: 1.2394 - val_accuracy: 0.8060
Epoch 238/250
4/4 [==============================] - 0s 14ms/step - loss: 0.0800 - accuracy: 0.9703 - val_loss: 1.2920 - val_accuracy: 0.7967
Epoch 239/250
4/4 [==============================] - 0s 15ms/step - loss: 0.1592 - accuracy: 0.9526 - val_loss: 1.3303 - val_accuracy: 0.7880
Epoch 

In [26]:
#Evaluating the model

scores = model.evaluate(test_x, test_y, verbose=0)

scores

# Extracting the accuracy from model.evaluate

print("%s: %.2f" % (model.metrics_names[0], scores[0]))
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

loss: 1.22
accuracy: 82.20%


# Keras DNN model 2

In [27]:
model = keras.models.Sequential()


inputlayer = keras.layers.Input(shape=12)

hidden1 = keras.layers.Dense(250, activation='relu')(inputlayer)
hidden2 = keras.layers.Dense(250, activation='relu')(hidden1)
hidden3 = keras.layers.Dense(250, activation='relu')(hidden2)



concat = keras.layers.Concatenate()([inputlayer, hidden3])

#final layer with 5 nodes and softmax (as we have 5 categories)
output = keras.layers.Dense(5, activation='softmax')(concat)

model = keras.Model(inputs =[inputlayer], outputs = output)

In [28]:
# Compiling model

#Optimizer:
adam = keras.optimizers.Adam(lr=0.01)

model.compile(loss='sparse_categorical_crossentropy', optimizer=adam, metrics=['accuracy'])

In [29]:
# Fitting the model

history = model.fit(train_x, train_y, 
                    validation_data=(test_x, test_y), 
                    epochs=241, batch_size=1000)

Epoch 1/241
4/4 [==============================] - 0s 50ms/step - loss: 1.4706 - accuracy: 0.3423 - val_loss: 1.1461 - val_accuracy: 0.5580
Epoch 2/241
4/4 [==============================] - 0s 15ms/step - loss: 1.1059 - accuracy: 0.5561 - val_loss: 1.0687 - val_accuracy: 0.5833
Epoch 3/241
4/4 [==============================] - 0s 16ms/step - loss: 1.0433 - accuracy: 0.5875 - val_loss: 0.9875 - val_accuracy: 0.6087
Epoch 4/241
4/4 [==============================] - 0s 16ms/step - loss: 0.9493 - accuracy: 0.6243 - val_loss: 0.9294 - val_accuracy: 0.6367
Epoch 5/241
4/4 [==============================] - 0s 17ms/step - loss: 0.9063 - accuracy: 0.6462 - val_loss: 0.8792 - val_accuracy: 0.6660
Epoch 6/241
4/4 [==============================] - 0s 15ms/step - loss: 0.8530 - accuracy: 0.6717 - val_loss: 0.8560 - val_accuracy: 0.6713
Epoch 7/241
4/4 [==============================] - 0s 16ms/step - loss: 0.8321 - accuracy: 0.6671 - val_loss: 0.8098 - val_accuracy: 0.6760
Epoch 8/241
4/4 [===

4/4 [==============================] - 0s 15ms/step - loss: 0.1467 - accuracy: 0.9453 - val_loss: 0.9451 - val_accuracy: 0.8053
Epoch 118/241
4/4 [==============================] - 0s 15ms/step - loss: 0.1423 - accuracy: 0.9472 - val_loss: 0.9071 - val_accuracy: 0.8193
Epoch 119/241
4/4 [==============================] - 0s 16ms/step - loss: 0.1489 - accuracy: 0.9447 - val_loss: 1.1339 - val_accuracy: 0.7873
Epoch 120/241
4/4 [==============================] - 0s 15ms/step - loss: 0.3440 - accuracy: 0.9201 - val_loss: 1.0189 - val_accuracy: 0.7753
Epoch 121/241
4/4 [==============================] - 0s 15ms/step - loss: 0.3760 - accuracy: 0.8929 - val_loss: 1.2585 - val_accuracy: 0.7767
Epoch 122/241
4/4 [==============================] - 0s 15ms/step - loss: 0.3948 - accuracy: 0.8927 - val_loss: 1.1208 - val_accuracy: 0.7907
Epoch 123/241
4/4 [==============================] - 0s 15ms/step - loss: 0.3557 - accuracy: 0.8895 - val_loss: 0.8699 - val_accuracy: 0.8013
Epoch 124/241
4/4 [=

Epoch 175/241
4/4 [==============================] - 0s 16ms/step - loss: 0.1256 - accuracy: 0.9519 - val_loss: 1.2439 - val_accuracy: 0.7807
Epoch 176/241
4/4 [==============================] - 0s 16ms/step - loss: 0.2001 - accuracy: 0.9370 - val_loss: 1.1984 - val_accuracy: 0.7720
Epoch 177/241
4/4 [==============================] - 0s 15ms/step - loss: 0.1941 - accuracy: 0.9331 - val_loss: 1.1042 - val_accuracy: 0.7907
Epoch 178/241
4/4 [==============================] - 0s 15ms/step - loss: 0.1366 - accuracy: 0.9454 - val_loss: 1.1487 - val_accuracy: 0.7907
Epoch 179/241
4/4 [==============================] - 0s 15ms/step - loss: 0.1552 - accuracy: 0.9405 - val_loss: 1.1545 - val_accuracy: 0.7913
Epoch 180/241
4/4 [==============================] - 0s 15ms/step - loss: 0.1463 - accuracy: 0.9416 - val_loss: 1.1037 - val_accuracy: 0.7920
Epoch 181/241
4/4 [==============================] - 0s 15ms/step - loss: 0.1366 - accuracy: 0.9493 - val_loss: 1.1092 - val_accuracy: 0.8000
Epoch 

Epoch 233/241
4/4 [==============================] - 0s 17ms/step - loss: 0.0960 - accuracy: 0.9708 - val_loss: 1.2522 - val_accuracy: 0.7973
Epoch 234/241
4/4 [==============================] - 0s 15ms/step - loss: 0.0905 - accuracy: 0.9625 - val_loss: 1.2215 - val_accuracy: 0.8133
Epoch 235/241
4/4 [==============================] - 0s 15ms/step - loss: 0.0904 - accuracy: 0.9694 - val_loss: 1.1912 - val_accuracy: 0.8113
Epoch 236/241
4/4 [==============================] - 0s 15ms/step - loss: 0.0665 - accuracy: 0.9787 - val_loss: 1.2463 - val_accuracy: 0.8053
Epoch 237/241
4/4 [==============================] - 0s 15ms/step - loss: 0.0830 - accuracy: 0.9692 - val_loss: 1.2520 - val_accuracy: 0.8227
Epoch 238/241
4/4 [==============================] - 0s 15ms/step - loss: 0.0759 - accuracy: 0.9781 - val_loss: 1.1928 - val_accuracy: 0.8213
Epoch 239/241
4/4 [==============================] - 0s 15ms/step - loss: 0.0604 - accuracy: 0.9818 - val_loss: 1.2138 - val_accuracy: 0.8233
Epoch 

In [30]:
# Evaluating the model

scores = model.evaluate(test_x, test_y, verbose=0)

scores

# Extracting the accuracy from model.evaluate

print("%s: %.2f" % (model.metrics_names[0], scores[0]))
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

loss: 1.22
accuracy: 82.27%


# MLPClassifier (one model for comparison purposes)

In [31]:
from sklearn.neural_network import MLPClassifier

#Default settings create 1 hidden layer with 100 neurons
mlp_clf = MLPClassifier(max_iter=1000, verbose=False,
                        hidden_layer_sizes=(250,250,250))

mlp_clf.fit(train_x, train_y)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


MLPClassifier(hidden_layer_sizes=(250, 250, 250), max_iter=1000)

In [32]:
from sklearn.metrics import accuracy_score
#Predicting the train values
train_y_pred = mlp_clf.predict(train_x)

#Train accuracy
accuracy_score(train_y, train_y_pred)

0.9368571428571428

In [33]:
#Predicting the test values
test_y_pred = mlp_clf.predict(test_x)

#Test accuracy
accuracy_score(test_y, test_y_pred)

0.8166666666666667